<<desc
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
desc

def fib(n)
  return 1 if n == 0 || n == 1
  return fib(n-1) + fib(n-2)
end

LIMIT = 4000000
pos = 0
sum = 0

sum += num if num % 2 == 0 while(num = fib(pos += 1)) < LIMIT

# 4613732

